name: Build & Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2016
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        shell: powershell
        run: |
          $vsPath = vswhere -latest `
            -prerelease `
            -products * `
            -requires Microsoft.Component.MSBuild `
            -property installationPath

          Write-Host "::set-env name=VS_PATH::${vsPath}"

          if ($vsPath) {
            $msBuildPath = join-path $vsPath "MSBuild\Current\Bin\"

            if (-not (test-path $msBuildPath)) {
              $msBuildPath = join-path $msBuildPath "MSBuild\15.0\Bin"

              if (-not (test-path $msBuildPath)) {
                throw "Failed to find MSBuild"
              }
            }

            Write-Host "::add-path::${msBuildPath}"
          } else {
            throw "Failed to find MSBuild"
          }

      - name: Build TiberianDawn.dll
        run: scripts/build-test.bat
