name: Build & Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2016
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Build TiberianDawn.dll
        run: scripts/build-test.bat
